apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "csp-collector.fullname" . }}
  labels:
    {{- include "csp-collector.labels" . | nindent 4 }}
    checksum/config: {{ include (print $.Template.BasePath "/configMap.yaml") . | sha256sum | trunc 63 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "csp-collector.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configMap.yaml") . | sha256sum | trunc 63 }}
      labels:
        {{- include "csp-collector.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
          - name: config-volume
            mountPath: /configs
          args:
            - "/csp_collector"
          {{- if .Values.custom.jsonOutput }}
            - "--output-format"
            - "json"
          {{- end }}
          {{- if .Values.custom.filterlist }}
            - "--filter-file"
            - "/configs/{{- .Values.custom.filterlist -}}"
          {{- end }}
          {{- if .Values.custom.graylogHost }}
            - "--graylog"
            - "{{- .Values.custom.graylogHost -}}"
          {{- end }}
          {{- if .Values.custom.debug }}
            - "--debug"
          {{- end }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /_healthcheck
              port: http
          readinessProbe:
            httpGet:
              path: /_healthcheck
              port: http
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
      volumes:
      - name: config-volume
        configMap:
          name: {{ template "csp-collector.fullname" . }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
